#    This workflow will:
#    - Do a clean install of node dependencies
#    - Run a local instance of mongoDB (DEFAULT PORT = 27017)
#    - Run tests across different versions of node and mongoDB

name: Node Mongo

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]
        mongodb-version: [4.2, 4.4]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Use MongoDB   
      uses: supercharge/mongodb-github-action@1.3.0   
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
      
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      env:
        DB_CONNECTION_STRING: "mongodb://localhost:27017/testDB"
        ACCESS_TOKEN_SECRET: "asdfghjkl"
